<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://polytech.unice.fr/si/4a/isa/bf" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://webservices/" name="InscrWebServiceImplService" targetNamespace="http://polytech.unice.fr/si/4a/isa/bf">
    <wsdl:import location="InscrWSType.wsdl" namespace="http://webservices/">
    </wsdl:import>
    <wsdl:binding name="InscrWebServiceImplServiceSoapBinding" type="ns1:InscrWebService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="addCoursP">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="addCoursP">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="addCoursPResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="creatParcours">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="creatParcours">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="creatParcoursResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="InscrWebServiceImplService">
        <wsdl:port binding="tns:InscrWebServiceImplServiceSoapBinding" name="InscrWebServiceImplPort">
            <soap:address location="http://localhost:8080/j2e-1.0-SNAPSHOT/webservices/InscrWS"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>